### What is Numpy??
The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array
object, and tools for working with these arrays.

In [1]:
import numpy as np

In [2]:
list = [1,2,3,4,5,"hi"]
list

[1, 2, 3, 4, 5, 'hi']

In [3]:
list = np.array([1,2,3,4,"Ashi"])
list

array(['1', '2', '3', '4', 'Ashi'], dtype='<U11')

In [4]:
list = np.array([1,2,3,4,5,6,7,8,9])
list

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
list1 = [[1,2,3],[4,5,6],[7,8,9]]
np.array(list1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
list1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
list1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [9]:
np.arange(20,1,-2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [10]:
np.arange(1.5,15,2)

array([ 1.5,  3.5,  5.5,  7.5,  9.5, 11.5, 13.5])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones(10 , dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
np.ones((3,2), dtype= int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [17]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [21]:
np.random.rand(2,3)

array([[0.32089063, 0.48860885, 0.39501881],
       [0.65904765, 0.49041873, 0.96392094]])

In [22]:
np.random.randn(2,3)

array([[-0.08603991, -1.05007501,  0.5392002 ],
       [-0.2923534 ,  0.88536812, -1.02565553]])

In [23]:
np.random.randint(1,10)

3

In [24]:
np.random.randint(1,10,30)

array([9, 5, 1, 2, 2, 7, 7, 7, 8, 4, 9, 5, 4, 4, 1, 3, 2, 2, 3, 4, 6, 7,
       9, 6, 6, 1, 2, 8, 8, 1])

In [25]:
sample_array=np.arange(50)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [26]:
rand_array=np.random.randint(0,100,20)
rand_array

array([27, 23, 22, 71,  7, 65, 69, 39, 86, 61, 48, 40, 13, 56, 99, 53, 59,
       73, 68, 61])

In [27]:
rand_array.reshape(4,5)

array([[27, 23, 22, 71,  7],
       [65, 69, 39, 86, 61],
       [48, 40, 13, 56, 99],
       [53, 59, 73, 68, 61]])

In [28]:
rand_array.reshape(5,4)

array([[27, 23, 22, 71],
       [ 7, 65, 69, 39],
       [86, 61, 48, 40],
       [13, 56, 99, 53],
       [59, 73, 68, 61]])

In [29]:
rand_array.max()

99

In [30]:
rand_array.min()

7

In [31]:
rand_array.argmax()

14

In [32]:
rand_array.argmin()

4

In [33]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
a.T

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
b = np.random.rand(2,4)
b

array([[0.22140985, 0.2136715 , 0.23167198, 0.67225072],
       [0.15084266, 0.14220413, 0.4570872 , 0.02457095]])

In [36]:
b.T

array([[0.22140985, 0.15084266],
       [0.2136715 , 0.14220413],
       [0.23167198, 0.4570872 ],
       [0.67225072, 0.02457095]])

In [37]:
sample_array=np.arange(1,51)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [38]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [39]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [40]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [41]:
sample_array[2:8]=100
sample_array

array([ 10,  11, 100, 100, 100, 100, 100, 100,  18,  19,  20])

### 2D Array

In [42]:
sample_matrix = np.array(([24,13,2,15],[15,54,65,23],[56,76,24,7]))
sample_matrix

array([[24, 13,  2, 15],
       [15, 54, 65, 23],
       [56, 76, 24,  7]])

In [43]:
sample_matrix[0][2]

2

In [44]:
sample_matrix[1][3]

23

In [45]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [63]:
sample_matrix[1:2,2:4]

array([[65, 23]])

In [47]:
sample_matrix[1:,2:]

array([[65, 23],
       [24,  7]])

In [48]:
sample_matrix[2]

array([56, 76, 24,  7])

In [50]:
sample_matrix[1]

array([15, 54, 65, 23])

In [51]:
sample_matrix

array([[24, 13,  2, 15],
       [15, 54, 65, 23],
       [56, 76, 24,  7]])

In [52]:
sample_array = np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [53]:
sample_array+ sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [54]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [55]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [56]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [57]:
np.max(sample_array)

30

In [58]:
np.min(sample_array)

1

In [59]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [60]:
np.argmax(sample_array)  # index of maximum value

29

In [61]:
np.argmin(sample_array)  # index of minimum value 

0

In [65]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [66]:
np.std(sample_array)

8.65544144839919

In [67]:
np.var(sample_array)

74.91666666666667

In [68]:
np.mean(sample_array)

15.5